config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :checklibs
  resources :icons


  resources :categories do
    resources :links
  end

  get 'welcome/index'

  root 'welcome#index'
  
  get '/daily', to: 'events#daily'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    serialize :recurring, Hash

    def recurring=(value)
      if value != "null" && RecurringSelect.is_valid_rule?(value)
        super(RecurringSelect.dirty_hash_to_rule(value).to_hash)
      else
        super(nil)
      end
    end

    def rule
      IceCube::Rule.from_hash recurring
    end

    def schedule(start)
      schedule = IceCube::Schedule.new(start)
      schedule.add_recurrence_rule(rule)
      schedule
    end

    def calendar_events(start)
      if recurring.empty?
        [self]
      else
        start_date = start.beginning_of_month.beginning_of_week
        end_date = start.end_of_month.end_of_week
        schedule(start_time).occurrences(end_date).map do |date|
          Event.new(id: id, name: name, start_time: date)
        end
      end
    end
  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @calendar_events = @events.flat_map{ |e| e.calendar_events(params.fetch(:start_date, Time.zone.now).to_date)}
  end


  def daily
    @events = Event.all
    @calendar_events = @events.flat_map{ |e| e.calendar_events(params.fetch(:start_date, Time.zone.now).to_date)}
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_time, :recurring)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :event_start_time %>
  </div>

  <div class="field">
    <%= form.label :recurring %>
    <%= form.select_recurring :recurring, nil, allow_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/daily.html.erb
<p id="notice"><%= notice %></p>



<%= calendar number_of_days: 1, events: @calendar_events do |date, events| %>
  <div><strong><%=date.to_s(:long) %> </strong></div>
  <% events.each do |event| %>
  <tr>
    <td>
  <%= link_to event.name, event_path(event.id)%>
</td><td>
  <%= event.start_time.strftime("%H:%M") %></td>
  <% end %>
<% end %>


<%= link_to 'New Event', new_event_path %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>


<%= month_calendar events: @calendar_events do|day, events| %>
  <div><strong><%=day.to_s(:long) %> </strong></div>

<div class="eventcount"> <%=events.count%> events </div>

  <% end %>

<br>
<%= link_to 'New Event', new_event_path %>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>Recurring</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.start_time %></td>
        <td><%= event.recurring %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>Recurring:</strong>
  <%= @event.recurring %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>