config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :checklibs
  resources :icons


  resources :categories do
    resources :links
  end

  get 'welcome/index'

  root 'welcome#index'
  
  get '/daily', to: 'events#daily'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/link.rb
class Link < ApplicationRecord

belongs_to :category

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @category = Category.find(params[:category_id])
    @links = @category.links
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
    @category = Category.find(params[:category_id])
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create


    @category = Category.find(params[:category_id])
    @link = Link.new(link_params)
    @link.category_id = params[:category_id]

    respond_to do |format|
      if @link.save
        format.html { redirect_to edit_category_path(@category), notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy

    @link.destroy

    respond_to do |format|
      format.html { redirect_to edit_category_path([@link.category]), notice: 'Link was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:name, :category_id, :link_url, :link_style, :icon_id)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for [@category, @link] do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link_name %>
    <%= form.text_field :name, id: :link_name %>
  </div>

  <div class="field">
    <%= form.label :link_url %>
    <%= form.text_field :link_url, id: :link_link_url %>
  </div>

  <div class="field">
    <%= form.label :link_style %>
    <%= form.text_field :link_style, id: :link_link_style %>
  </div>

  <div class="field">
    <%= form.label :icon_id %>
    <%= form.number_field :icon_id, id: :link_icon_id %>
  </div>

 <%= link.inspect %>
    <%= form.hidden_field :category_id%>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_index.html.erb
<p id="notice"><%= notice %></p>

    <% category.links.each do |link| %>

      <%= link_to 'NAME', "http://#{link.link_url}", class: "navitem", target: "_blank"%>








        <%= link_to 'Show', link %>
        <%= link_to 'Edit', edit_link_path(link) %>
        <%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %>

    <% end %>


<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>Link name</th>
      <th>Link url</th>
      <th>Link style</th>
      <th>Icon</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>

        <td><%= link.name %></td>
        <td><%= link.link_style %></td>
        <td><%= link.icon_id %></td>
        <td><%= link.category_id %></td>
        <td><%= link_to 'Show', category_link_path(@category, link) %></td>
        <td><%= link_to 'Edit', edit_category_link_path(@category, link) %></td>
        <td><%= link_to 'Destroy', category_link_path(@category, link), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', category_links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link url:</strong>
  <%= @link.link_url %>
</p>

<p>
  <strong>Link style:</strong>
  <%= @link.link_style %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @link.icon_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @link.category_id %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>