config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :checklibs
  resources :icons


  resources :categories do
    resources :links
  end

  get 'welcome/index'

  root 'welcome#index'
  
  get '/daily', to: 'events#daily'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
belongs_to :icon
has_many :links


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]


@icons = Icon.all
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @icons = Icon.all

  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    @icons = Icon.all
    @icon = Icon.new
    @link = Link.new(category_id: params[:category_id])
  end

  # GET /categories/1/edit
  def edit

    @icons = Icon.all
    @icon = Icon.new
    @link = Link.new( :category => @category)
end
  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @icons = Icon.all
    @icon = Icon.new


    respond_to do |format|
      if @category.save
        format.html { redirect_to edit_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to root_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :icon_id, :user_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
<% if category.errors.any? %>
<div id="error_explanation">
   <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
   <ul>
      <% category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
   </ul>
</div>
<% end %>
<div style="margin:auto;width:100%">
   <div class="row justify-content-between row-eq-height">
      <div class="col" style="padding:10px;max-height:300px">
         <div class="card text-white mb-3">
            <div class="card-header bg-primary">
               <h4>Icon Library</h4>
            </div>
            <div class="list-group bg-secondary" style="max-height:200px;overflow:scroll">
               <% @icons.each do |icon| %>
               <div class="list-group-item-active text-white">
                  <i class="fa fa-<%= icon.name %>" aria-hidden="true" style="color:white;"></i> <%= icon.name %>
               </div>
               <% end %>
            </div>
            <div class="card-footer">
               <%= link_to 'Edit Icons', icons_path, class: "btn btn-primary btn-lg btn-block", type:"button" %>
            </div>
         </div>
      </div>



      <div class="col" style="margin:0;padding:10px;min-width:250px">
         <div class="card" style="min-height:300px">
            <div class="card-header bg-primary row justify-content-center">
                <div class="col-6" style="padding:0;min-width:150px;">
                    <div class="d-inline-flex">
                     <i class="fa fa-<%= category.icon.try(:name)%>" aria-hidden="true" style="color:white;font-size:24px;margin-right:10px;display:inline-block;"></i>

                     <%= form.select :icon_id, options_for_select(@icons.collect { | icon | [icon.name, icon.id] }, @icon.id), {}, {class: "form-control"} %>
                   </div>
             </div>
               <div class="col-6" style="padding:0;min-width:150px;">
                  <%= form.text_field :name, id: :category_name, class:"form-control"%>
               </div>

         </div>
         <div class="card-body bg-secondary row justify-content-center">
            <% category.links.each do |link| %>
            <%= link_to category_link_path(@category, link), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary col-xs-2", id:"parent",style:"margin:5px;width:150px;" do%>
            <div class="parent_hide"><%= link.name %></div>
            <div class="parent_show"> Delete </div>
            </button>
            <%end%>
            <% end %>
            <%= if !@category.new_record?
               link_to "New Link", new_category_link_path(category_id: @category.id), class: "btn btn-primary col-xs-2 bg-success border-success", type:"button", style:"margin:5px;width:150px;"
               end %>
         </div>
      </div>
      <div>
      </div>
   </div>
   <br>

   <%= form.submit 'Submit', class: "btn btn-primary btn-block", style:"margin-top:100px"%>
</div>
</div>
<div class="field"></div>
<%= form.hidden_field :user_id, id: :category_user_id %>
<% end %>
</div>
</div>

app/views/categories/_index.html.erb
<p id="notice"><%= notice %></p>




  <% @categories.each do |category| %>
    <div class="card" style="width:100%;">
      <div class="card-header bg-primary row justify-content-between align-items-center" >
        <div class="col-auto">
          <i class="fa fa-<%= category.icon.try(:name)%>" aria-hidden="true" style="color:white;"></i> <%= category.name %>
        </div>

            <div class="dropup btn-group">
           <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" >
             Options
           </button>
              <div class="dropdown-menu" style="margin:0;padding:0;width:50px">

                  <%= link_to edit_category_path(category), class: "btn-block btn-primary", style:"margin:0;padding:5px;" do %>
                      <i class="fa fa-cogs"></i>    Options
                  <% end %>

                  <%= link_to category, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn-block btn-primary", style:"margin:0;padding:5px" do %>
                      <i class="fa fa-trash"></i> Delete
                  <% end %>

              </div>
            </div>


        </div>
            <div class="card-body bg-secondary row justify-content-center">
              <% category.links.each do |link| %>
                <%= link_to link.name, "http://#{link.link_url}", class: "btn btn-primary col-md-2", type:"button", target: "_blank", style:"margin:5px;min-width:200px;"%>
              <% end %>
            </div>
          </div>
<br>
  <% end %>

app/views/categories/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron", style="min-width:260px;margin:0;padding:5px">

<h1>Editing Category</h1>

<%= render 'form', category: @category%>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>




    <% @categories.each do |category| %>
    <div class="category_container">
    <div class="category_header">
<%= category.icon.inspect %>
      <div>
         <i class="<%= category.icon %>" aria-hidden="true" style="color:white;"> <%= category.name %>
      </div>


       <div class="options_container">

         <div class="btn-group dropup">
           <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Options
           </button>
           <div class="dropdown-menu">
             <%= link_to 'Edit', edit_category_path(category) %>
             <br>
             <%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %>
           </div>
         </div>


        </div>
    </div>


    <Div class="access_container">

      <% category.links.each do |link| %>

          <%= link_to 'NAME', "http://#{link.link_url}", class: "navitem", target: "_blank"%>


      <% end %>

    </div>
    </div>
    <% end %>

<br>
<div class="new_category_wrapper">
<%= link_to '+', new_category_path, class: "new_category" %>
</div>

app/views/categories/new.html.erb
<div class="jumbotron", style="padding:15px">

<h1>New Category</h1>

<%= render 'form', category: @category %>
</div>
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @category.icon_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @category.user_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>