config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :checklibs
  resources :icons


  resources :categories do
    resources :links
  end

  get 'welcome/index'

  root 'welcome#index'
  
  get '/daily', to: 'events#daily'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/icon.rb
class Icon < ApplicationRecord
has_many :categories


  before_save { |icon| icon.name = name.downcase }
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  before_action :set_icon, only: [:show, :edit, :update, :destroy]

  # GET /icons
  # GET /icons.json
  def index
    @icons = Icon.all
  end

  # GET /icons/1
  # GET /icons/1.json
  def show
  end

  # GET /icons/new
  def new
    @icon = Icon.new
  end

  # GET /icons/1/edit
  def edit
  end

  # POST /icons
  # POST /icons.json
  def create
    @icon = Icon.new(icon_params)

    respond_to do |format|
      if @icon.save
        format.html { redirect_to @icon, notice: 'Icon was successfully created.' }
        format.json { render :show, status: :created, location: @icon }
      else
        format.html { render :new }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /icons/1
  # PATCH/PUT /icons/1.json
  def update
    respond_to do |format|
      if @icon.update(icon_params)
        format.html { redirect_to @icon, notice: 'Icon was successfully updated.' }
        format.json { render :show, status: :ok, location: @icon }
      else
        format.html { render :edit }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icons/1
  # DELETE /icons/1.json
  def destroy
    @icon.destroy
    respond_to do |format|
      format.html { redirect_to icons_url, notice: 'Icon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icon
      @icon = Icon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def icon_params
      params.require(:icon).permit(:name, :path)
    end
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/views/icons/_form.html.erb
<%= form_with(model: icon, local: true) do |form| %>
  <% if icon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(icon.errors.count, "error") %> prohibited this icon from being saved:</h2>

      <ul>
      <% icon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field">

    <%= form.label :name %>
    <%= form.text_field :name, id: :icon_name %>
  </div>

  <div class="actions">


    <%= form.submit 'Submit', class: "btn btn-primary"%>
  </div>
<% end %>

app/views/icons/edit.html.erb
<div class="jumbotron", style="padding:15px">
<h1>Editing Icon</h1>

<%= render 'form', icon: @icon %>
</div>
<%= link_to 'Show', @icon %> |
<%= link_to 'Back', icons_path %>

app/views/icons/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Icons</h1>
<br>
<div class="jumbotron">
   <div class="row justify-content-center" style="margin:15px;">
      <% @icons.each do |icon| %>
      <div class="container col-sm-1" style="min-width:150px; background-color:grey;margin:5px; height:70px">
         <div class="align-top">
            <%= icon.id %> <i class="fa fa-<%= icon.name %>" aria-hidden="true"></i>
         </div>
         <div class="align-middle">
            <%=icon.name %>
         </div>
         <%= link_to 'Delete', icon, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <% end %>
   </div>
</div>
<div>
   <%= link_to 'New Icon', new_icon_path %>
</div>
</div>

app/views/icons/new.html.erb
<div class="jumbotron", style="padding:15px">
<h1>New Icon</h1>

<%= render 'form', icon: @icon %>
</div>
<%= link_to 'Back', icons_path %>

app/views/icons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Path:</strong>
  <%= @icon.path %>
</p>

<%= link_to 'Edit', edit_icon_path(@icon) %> |
<%= link_to 'Back', icons_path %>